### ISSUE TITLE
Static pages, template system

### ISSUE THREAD

**Issue by falkreon** [ionch/ionch#2]
## Static Resources

We need to designate a folder in the server directory for static resources and serve them when requested. This will serve emoji, user icons, and anything else that doesn't change from moment to moment. It's also important to the overall all-in-one strategy to prevent ionch administrators from having to install apache or nginx alongside each and every instance.

* If a RestHandler claims the resource (returns `true` from `matches`) but does not generate a response, the resource should be off-limits for static and templated pages. This prevents accidental use of fallback pages in, for instance, `/.well-known/`.

## Templates

We also need a *simple* template system that can specify placeholders for included elements. Some of these elements will be text and will need to be http-encoded so they don't break formatting. Other elements will be HTML and will need to not be http-encoded because they're generated by sub-templates (such as Notes in a Timeline). I'd almost say this was a job for XSLT, except then we'd need to convert a lot of json data to XML.

* There should be some difference between "include a resource at this location", and "mark where an automated inclusion should go". In a Note, a name will be injected. Let's say the placeholder is called `person.name` It should never be possible to accidentally include a page named "person.name.html" in that location.

* Accessibility and hackability is key. If it already exists in the wild, is simple to pick up and learn, and doesn't add to installation complexity, we should use that instead of rolling our own.

**Comment by exaskye** [comment]
Handlebars is probably a good choice of template engine, or is at least my recommendation.

For static files we'll basically want to serve things from the filesystem and classpath, in that order, so admins can override resources, without requiring extraction or a multifile distribution.

**Comment by falkreon** [comment]
good call, including starter pages and templates directly in the jar resources dir. Will look into handlebars.

**Comment by falkreon** [comment]
Looks like the base syntax is almost exactly the sort of thing I was hoping for, and there's already a Java implementation under Apache 2.0 - by my estimation the license is compatible with shadowing and distribution with the server.
https://github.com/jknack/handlebars.java

The only thing that's rough around the edges is the page inclusion, which seems to revolve around "partials". It's not clear to me what files if any will be scouted for inclusion by `{{> foo }}`, and the "parent context" bits are pretty opaque. I'd suggest that we don't use very complex handlebars verbiage unless we had to.

**Comment by exaskye** [comment]
Closing due to project restart in ba33c85.
